name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login into Dockerhub
      run: echo "${{ secrets.DOCKERPW }}" | docker login -u "lijozech12" --password-stdin
    - name: build preprocessing Image
      run: docker build ./preprocessing_step --tag lijozech12/preprocess:latest
    - name: push preprocessing Image
      run: docker push lijozech12/preprocess:latest
    
    
