name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login into Dockerhub
      run: echo "${{ secrets.DOCKERPW }}" | docker login -u "lijozech12" --password-stdin
    - name: build preprocessing Image
      run: docker build ./preprocessing_step --tag lijozech12/boston_pipeline_images:preprocess
    - name: push preprocessing Image
      run: docker push lijozech12/boston_pipeline_images:preprocess
    - name: build Training Image
      run: docker build ./preprocessing_step --tag lijozech12/boston_pipeline_images:train
    - name: push Training Image
      run: docker push lijozech12/boston_pipeline_images:train
    - name: build Testing Image
      run: docker build ./preprocessing_step --tag lijozech12/boston_pipeline_images:test
    - name: push Testing Image
      run: docker push lijozech12/boston_pipeline_images:test
    - name: build deploy Image
      run: docker build ./deploying_step --tag lijozech12/boston_pipeline_images:deploy_model
    - name: push deploy Image
      run: docker push lijozech12/boston_pipeline_images:deploy_model
    
    
