name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login into Dockerhub
      run: echo "${{ secrets.DOCKERPW }}" | docker login -u "lijozech12" --password-stdin
    - name: build preprocessing Image
      run: docker build ./Steps/preprocessing_step --tag lijozech12/preprocess:latest
    - name: push preprocessing Image
      run: docker push lijozech12/preprocess:latest
    - name: build Training Image
      run: docker build ./Steps/training_step --tag lijozech12/train:latest
    - name: push Training Image
      run: docker push lijozech12/train:latest
    - name: build Testing Image
      run: docker build ./Steps/testing_step --tag lijozech12/test:latest
    - name: push Testing Image
      run: docker push lijozech12/test:latest
    - name: build deploy Image
      run: docker build ./Steps/deploying_step --tag lijozech12/deploy_model:latest
    - name: push deploy Image
      run: docker push lijozech12/deploy_model:latest
    
    
